// generated by ../php-to-scala/php-to-scala.php on 2010-04-27T19:49:24-05:00

import php._;
import scala.Predef.{ any2ArrowAssoc => _ }

object test_0_php extends php.script {
  override def include {
var i: integer = 0;

  echo("Hello, World\n");

  
i=1;
while( i <= 3) {
 { 
   echo(i);
   echo("\n");
   };
 (i = i + 1)
}


  }
}
